name: CI for testing
on:
  workflow_dispatch:
    inputs:

env:
  ENV_PLACEHOLDER: 'something'

jobs:
  TestWorkflowJob:
    runs-on: [ self-hosted, on-prem ]
    steps:
      - name: Debug the folder
        run: |
          ls -al
      - name: Echo command
        run: |
          echo 'Test Echo'